
include ../../example.mk

WP_TIMEOUT=25

#WP_FLAGS += -wp-split
#WP_FLAGS += -wp-prop=increasing
#WP_FLAGS += -wp-prop=reorder
#WP_FLAGS += -wp-prop=unchanged
#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop="-@assert"

