
FILE=pop_heap
CMD=\\popheap
SEC=sec:pop_heap

include ../../Makefile.template

#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop="-reorder"
#WP_FLAGS += -wp-fct pop_heap
#WP_FLAGS += -wp-fct find_child
#WP_FLAGS += -wp-prop rte
#WP_FLAGS += -wp-prop heap
#WP_FLAGS += -wp-prop max

TESTOBJ += -lheap


