
include ../../Config/example.mk

WP_TIMEOUT=5

#WP_FLAGS += -wp-prop HeapMaximum
#WP_FLAGS += -wp-prop compatible
#WP_FLAGS += -wp-prop upper
#WP_FLAGS += -wp-prop max
#WP_FLAGS += -wp-prop heap
#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop="@lemma"
#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop reorder
#WP_FLAGS += -wp-prop="-reorder"
#WP_FLAGS += -wp-fct pop_heap

#WP_FLAGS += -wp-fct pop_heap
#WP_FLAGS += -wp-prop rte
#WP_FLAGS += -wp-prop HeapMaximum

