
include ../../example.mk

#WP_FLAGS += -wp-prop PopHeapUpdate
#WP_FLAGS += -wp-prop heap
#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop="@lemma"
#WP_FLAGS += -wp-prop="-reorder"
#WP_FLAGS += -wp-fct pop_heap

#WP_FLAGS += -wp-fct maximum_heap_child
#WP_FLAGS += -wp-prop rte
#WP_FLAGS += -wp-prop HeapMaximum
#WP_FLAGS += -wp-prop max

TESTOBJ += -lheap

