
# Makefile (directory-local configuration)

TOP_DIR    ?= $(abspath ..)
CONFIG_DIR := $(TOP_DIR)/Config

include $(CONFIG_DIR)/examples.mk

# set special timeout
pop_heap.wp pop_heap.wplog: WP_TIMEOUT = 4

