
FILE=insertion_sort
CMD=\\insertionsort
SEC=sec:insertion_sort

#WP_TIMEOUT=20

include ../../Makefile.template

#WP_FLAGS += -wp-prop=sorted
#WP_FLAGS += -wp-prop=reorder
#WP_FLAGS += -wp-prop=unchanged
#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop="-@assert"

TESTOBJ += -lbinarysearch -lmutating


