
FILE=unique_copy
CMD=\\uniquecopy
SEC=sec:uniquecopy

include ../../Makefile.template
CPPFLAGS += -I../unique_copy_tests

#WP_FLAGS += -wp-prop  unique
#WP_FLAGS += -wp-prop @assert
#WP_FLAGS += -wp-prop @lemma

