
FILE=partial_sort_copy
CMD=\\partialsortcopy
SEC=sec:partial_sort_copy

#WP_TIMEOUT=20

include ../../Makefile.template

WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop=@lemma
#WP_FLAGS += -wp-prop HeapMaximum

#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop reorder

#WP_FLAGS += -wp-prop lower
#WP_FLAGS += -wp-prop upper
#WP_FLAGS += -wp-prop partition


TESTOBJ += -lheap -lmutating

