
FILE=remove_copy2
CMD=\\removecopy2
SEC=sec:removecopy2

include ../../Makefile.template

#WP_TIMEOUT=20

#WP_FLAGS  += -wp-fct remove_copy_aux
#WP_FLAGS  += -wp-fct remove_copy

#WP_FLAGS += -wp-prop  bound
#WP_FLAGS += -wp-prop  size
#WP_FLAGS += -wp-prop  mapping
#WP_FLAGS += -wp-prop retain
#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop @lemma
#WP_FLAGS += -wp-prop="-@lemma"


