
CMD=\\removecopytwo
SEC=sec:removecopy2

include ../../example.mk

#WP_TIMEOUT=10
#WP_FLAGS += -wp-prop @lemma
#WP_FLAGS += -wp-prop="-@lemma"

#WP_FLAGS += -wp-prop  bound
#WP_FLAGS += -wp-prop  size
#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop @assert


