FILE=remove_copy2
CMD=\\removecopy\(2\)
SEC=sec:removecopy2

include ../../Makefile.template

WP_FLAGS += -wp-split

#WP_FLAGS +=  -wp-prop stable
#WP_FLAGS +=  -wp-prop result
#WP_FLAGS +=  -wp-prop @lemma
#WP_FLAGS += -wp-prop="-@lemma"


