
FILE=adjacent_difference_inverse
CMD=\\adjacentdifferenceinverse
SEC=sec:inverting-adjacentdifference

include ../../Makefile.template

TESTOBJ += -lnumeric

#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop @lemma


