
CMD=\\equalrangetwo
SEC=sec:equalrange2

include ../../example.mk

#WP_FLAGS+=-wp-prop right
#WP_FLAGS+=-wp-prop StrictLowerBoundExpansion
#WP_FLAGS+=-wp-prop TwoSidedBound
#WP_FLAGS+=-wp-prop @lemma
#WP_FLAGS+=-wp-prop="-@lemma"
#WP_FLAGS+=-wp-prop ConstantRange
#WP_FLAGS+=-wp-prop StrictUpper
#WP_FLAGS+=-wp-prop StrictLower

