
FILE=equal_range2
CMD=\\equalrange\(2\)
SEC=sec:equalrange2

include ../../Makefile.template

#WP_FLAGS+=-wp-prop right
#WP_FLAGS+=-wp-prop StrictLowerBoundExpansion
#WP_FLAGS+=-wp-prop TwoSidedBound
#WP_FLAGS+=-wp-prop @lemma
#WP_FLAGS+=-wp-prop="-@lemma"
#WP_FLAGS+=-wp-prop ConstantRange
#WP_FLAGS+=-wp-prop StrictUpper
#WP_FLAGS+=-wp-prop StrictLower

TESTOBJ += -lbinarysearch

