
FILE=adjacent_difference
CMD=\\adjacentdifference
SEC=sec:adjacentdifference

include ../../Makefile.template

#WP_FLAGS += -wp-fct adjacent_difference
#WP_FLAGS += -wp-prop rte
#WP_FLAGS += -wp-prop after
#WP_FLAGS += -wp-prop difference
#WP_FLAGS += -wp-prop @lemma

TESTOBJ += -lnumeric

