
FILE=remove_copy
CMD=\\removecopy
SEC=sec:removecopy

include ../../Makefile.template

#WP_FLAGS += -wp-prop RetainAllButOneMiss
#WP_FLAGS += -wp-prop retain
#WP_FLAGS += -wp-prop  bound
#WP_FLAGS += -wp-prop  result
#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-bhv not_equal
#WP_FLAGS += -wp-prop @assert
#WP_FLAGS += -wp-prop @lemma


