
FILE=remove_copy
CMD=\\removecopy
SEC=sec:removecopy

WP_TIMEOUT = 30

include ../../Makefile.template

#WP_FLAGS += -wp-prop discard
#WP_FLAGS += -wp-prop retain
#WP_FLAGS += -wp-prop  bound
#WP_FLAGS += -wp-prop  result
#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-bhv not_equal
WP_FLAGS += -wp-split

