
include ../../example.mk

# verify "first"
#WP_FLAGS += -wp-prop first

# verify all but "first"
# WP_FLAGS += -wp-prop="-first"

# verify only lemmas
#WP_FLAGS += -wp-prop @lemma

# verify everything but lemmas
#WP_FLAGS += -wp-prop="-@lemma"

