
FILE=rotate
CMD=\\ALGrotate
SEC=sec:rotate

include ../../Makefile.template

#WP_FLAGS += -wp-prop left
#WP_FLAGS += -wp-prop middle
#WP_FLAGS += -wp-prop right

#WP_FLAGS += -wp-prop="@lemma"

#WP_FLAGS += -wp-prop ReverseIdempotentRight
#WP_FLAGS += -wp-fct rotate

TESTOBJ += -lmutating

