
include ../../Config/example.mk

WP_TIMEOUT=2

#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop Remove_Update
#WP_FLAGS += -wp-prop interval
#WP_FLAGS += -wp-prop @lemma
#WP_FLAGS += -wp-prop="-@lemma"

