
include ../../example.mk

WP_TIMEOUT=40
#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop remove
#WP_FLAGS += -wp-prop Remove_Update
#WP_FLAGS += -wp-prop  bound
#WP_FLAGS += -wp-prop  result
#WP_FLAGS += -wp-prop @lemma
#WP_FLAGS += -wp-prop="-@lemma"

