
include ../../Config/example.mk

#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop remove
#WP_FLAGS += -wp-prop Remove_Update
#WP_FLAGS += -wp-prop interval
#WP_FLAGS += -wp-prop  result
#WP_FLAGS += -wp-prop @lemma
#WP_FLAGS += -wp-prop="-@lemma"

