
CMD=\\uniquecopytwo
SEC=sec:uniquecopy2
TEST_DATA=../unique_copy_tests/test-data-compare.txt

include ../../example.mk
CPPFLAGS += -I../unique_copy_tests

report: unique_copy2.normal.c unique_copy2.normal-rte.c
preport: unique_copy2.normal.c unique_copy2.normal-rte.c

#WP_FLAGS += -wp-prop  bound
#WP_FLAGS += -wp-prop @assert
#WP_FLAGS += -wp-prop @lemma

