#!/usr/bin/env python3

from sys import argv, exit
from datetime import datetime
from os import listdir
from os.path import isdir, isfile, join
from fnmatch import fnmatch
import re

from normalize import normalize

if len(argv) != 2:
    exit("Please, specify the folder with *.acsl files.\nUsage: {} <folder>".
         format(argv[0]))

dir = argv[1]

if not isdir(dir):
    exit("Can't find dir: {}".format(dir))

logic_def = re.compile(
    r"""
\b
	(?:
		lemma|axiom(?:atic)?|
		predicate|inductive|type|
		logic[\wℤ𝔹\s\*]+
	)
\s*\b
	([a-zA-Z_]\w*)""", re.X)


def find_acsl_names(file):
    with open(file, 'r') as fh:
        content = fh.read()
        return logic_def.findall(content)


names = []
for file in listdir(dir):
    path = join(dir, file)
    if fnmatch(file, '*.acsl') and isfile(path):
        names += find_acsl_names(path)

print()
print("% This file has been automatically generated by {}".format(argv[0]))
print("% {}".format(datetime.now()))
print()

for name in sorted(set(names)):
    print('\\newcommand{\\' + normalize(name) + '}{\\mbox{\\inl{' + name +
          '}}\\xspace}')

print()
