#!/usr/bin/env python3

from sys import argv, exit
from datetime import datetime
from os import listdir
from os.path import isdir, isfile, join, basename
from fnmatch import fnmatch
from adjust_name import adjust_name
import re

if len(argv) != 2:
    exit("Please, specify the folder with *.c files .\nUsage: {} <folder>".
         format(argv[0]))

dir = argv[1]

if not isdir(dir):
    exit("Can't find dir: {}".format(dir))

names = []
for file in listdir(dir):
    path = join(dir, file)
    if fnmatch(file, '*.c') and isfile(path):
        names.append(file)

print()
print("% This file has been automatically generated by {}".format(argv[0]))
print("% {}".format(datetime.now()))
print()

for fullname in sorted(set(names)):
    name = fullname.replace('.c', '')
    command = adjust_name(name)

    # deal with files of "normal forms"
    command = command.replace('.', '')
    print('\\newcommand{\\' + command + '}{\\mbox{\\inl{' + name +
          '}}\\xspace}')

print()
