
FILE=selection_sort
CMD=\\selectionsort
SEC=sec:selection_sort

export WP_TIMEOUT=10

include ../../Makefile.template

#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop reorder
#WP_FLAGS += -wp-prop sorted
#WP_FLAGS += -wp-prop SwapImpliesMultisetUnchanged
#WP_FLAGS += -wp-prop "UpperBoundShift"
#WP_FLAGS += -wp-prop "StrictUpperBoundShift"

TESTOBJ += -lmaxmin -lmutating


