
CMD=\\partialsort
SEC=sec:partial_sort


include ../../Makefile.template

#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop=@lemma

#WP_FLAGS += -wp-prop CountSectionPositive
#WP_FLAGS += -wp-prop PositiveCountImpliesHasValue
#WP_FLAGS += -wp-prop ReorderImpliesMatch
#WP_FLAGS += -wp-prop ReorderPreservesLowerBound

#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop reorder

#WP_FLAGS += -wp-prop lower
#WP_FLAGS += -wp-prop upper
#WP_FLAGS += -wp-prop partition


TESTOBJ += -lheap -lmutating

