
FILE=push_heap
CMD=\\pushheap
SEC=sec:push_heap


include ../../Makefile.template

#WP_FLAGS += -wp-prop="@lemma"
#WP_FLAGS += -wp-prop="-@lemma"

#WP_FLAGS += -wp-prop MultsetAddDistinct
#WP_FLAGS += -wp-prop MultisetUnchangedExceptLemma
#WP_FLAGS += -wp-prop heap
#WP_FLAGS += -wp-prop="-heap"
#WP_FLAGS += -wp-prop except
#WP_FLAGS += -wp-prop reorder
#WP_FLAGS += -wp-prop="-reorder"
#WP_FLAGS += -wp-prop positive
#WP_FLAGS += -wp-prop bound
#WP_FLAGS += -wp-prop less
#WP_FLAGS += -wp-prop decreasing
#WP_FLAGS += -wp-prop val
#WP_FLAGS += -wp-prop parent
#WP_FLAGS += -wp-prop hole
#WP_FLAGS += -wp-prop rte
#WP_FLAGS += -wp-prop @assigns
#WP_FLAGS += -wp-prop="-@invariant"

TESTOBJ += -lheap

