
include ../../Config/example.mk

WP_TIMEOUT=5
#WP_FLAGS += -wp-prop="@lemma"
#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop @assigns
#WP_FLAGS += -wp-prop="-@invariant"

#WP_FLAGS += -wp-prop heap
#WP_FLAGS += -wp-prop="-heap"
#WP_FLAGS += -wp-prop minus
#WP_FLAGS += -wp-prop reorder
#WP_FLAGS += -wp-prop MultsetAddDistinct
#WP_FLAGS += -wp-prop rte
