
FILE=push_heap
CMD=\\pushheap
SEC=sec:push_heap

include ../../Makefile.template

#WP_FLAGS += -wp-prop heap
#WP_FLAGS += -wp-prop reorderother
#WP_FLAGS += -wp-prop reorderhole
#WP_FLAGS += -wp-prop reorderval
#WP_FLAGS += -wp-prop reorder
#WP_FLAGS += -wp-prop positive
#WP_FLAGS += -wp-prop bound
#WP_FLAGS += -wp-prop less
#WP_FLAGS += -wp-prop decreasing
#WP_FLAGS += -wp-prop valid
#WP_FLAGS += -wp-prop val
#WP_FLAGS += -wp-prop parent
#WP_FLAGS += -wp-prop hole
#WP_FLAGS += -wp-prop newhole
#WP_FLAGS += -wp-prop="@invariant"
#WP_FLAGS += -wp-prop="@lemma"
#WP_FLAGS += -wp-prop @assigns
#WP_FLAGS += -wp-prop rte
#WP_FLAGS += -wp-prop foo
#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop="-reorder"
#WP_FLAGS += -wp-prop="-heap"


