
FILE=partial_sum
CMD=\\partialsum
SEC=sec:partialsum

include ../../Makefile.template

#WP_FLAGS += -wp-prop accumulate
#WP_FLAGS += -wp-prop partialsum
#WP_FLAGS += -wp-prop @lemma

TESTOBJ += -lnumeric

