
CMD=\\partialsum
SEC=sec:partialsum

export WP_TIMEOUT=20

include ../../Makefile.template

#WP_FLAGS += -wp-prop rte
#WP_FLAGS += -wp-prop partialsum
#WP_FLAGS += -wp-prop @lemma

TESTOBJ += -lnumeric

