
FILE=unique_copy2
CMD=\\uniquecopy\(2\)
SEC=sec:uniquecopy2

WP_TIMEOUT=15

include ../../Makefile.template
CPPFLAGS += -I../unique_copy_tests

#WP_FLAGS += -wp-prop  UniquePreserve
#WP_FLAGS += -wp-prop  unique
#WP_FLAGS += -wp-prop @assert
#WP_FLAGS += -wp-prop @lemma
#WP_FLAGS += -wp-prop  mapping
#WP_FLAGS += -wp-prop  unique
#WP_FLAGS += -wp-prop  UniquePartitionDiffer
#WP_FLAGS += -wp-prop  size
#WP_FLAGS += -wp-prop  copy
#WP_FLAGS += -wp-prop="-@lemma"

