CMD=\\merge
SEC=sec:merge

include ../../Makefile.template

#WP_FLAGS += -wp-prop=sorted
#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop="-@assert"

WP_FLAGS += -wp-split

TESTOBJ += -lmutating


