

include ../../example.mk

#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop reorder
#WP_FLAGS += -wp-prop sorted
#WP_FLAGS += -wp-prop SwapImpliesMultisetUnchanged
#WP_FLAGS += -wp-prop "UpperBoundShift"
#WP_FLAGS += -wp-prop "StrictUpperBoundShift"

