
CMD=\\uniquecopy
SEC=sec:uniquecopy
TEST_DATA=../unique_copy_tests/test-data-compare.txt

include ../../Makefile.template
CPPFLAGS += -I../unique_copy_tests

#WP_FLAGS += -wp-prop  bound
#WP_FLAGS += -wp-prop @assert
#WP_FLAGS += -wp-prop @lemma


