
CMD=\\uniquecopythree
SEC=sec:uniquecopy3
TEST_DATA=../unique_copy_tests/test-data-compare.txt

include ../../Makefile.template
CPPFLAGS += -I../unique_copy_tests

#WP_FLAGS += -wp-prop  unique
#WP_FLAGS += -wp-prop @assert
#WP_FLAGS += -wp-prop @lemma

