
CMD=\\uniquecopyfour
SEC=sec:uniquecopy4
TEST_DATA=../unique_copy_tests/test-data-compare.txt


include ../../example.mk
CPPFLAGS += -I../unique_copy_tests

#WP_FLAGS += -wp-split
#WP_FLAGS += -wp-prop  UniquePreserve
#WP_FLAGS += -wp-prop  unique
#WP_FLAGS += -wp-prop @assert
#WP_FLAGS += -wp-prop @lemma
#WP_FLAGS += -wp-prop  bound
#WP_FLAGS += -wp-prop  size
#WP_FLAGS += -wp-prop  unchanged
#WP_FLAGS += -wp-prop  mapping
#WP_FLAGS += -wp-prop="-@lemma"

