
FILE=sort_heap
CMD=\\sortheap
SEC=sec:sort_heap

include ../../Makefile.template

#WP_FLAGS += -wp-prop heap
#WP_FLAGS += -wp-prop reorder
#WP_FLAGS += -wp-prop max
#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop @lemma
#WP_FLAGS += -wp-prop="-@lemma"

TESTOBJ += -lheap ../pop_heap/pop_heap.o

