
include ../../Config/example.mk

#WP_FLAGS += -wp-prop reorder
#WP_FLAGS += -wp-prop max
#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-prop @lemma
#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop HeapBounds
#WP_FLAGS += -wp-prop HeapMaximum

