
CMD=\\randomshuffle
SEC=sec:randomshuffle


include ../../Makefile.template

# disable -warn-unsigned-overflow
WP_RTE_FLAGS=-warn-unsigned-downcast

#WP_FLAGS  += -wp-prop lower
#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-split
#WP_FLAGS  += -wp-fct random_shuffle
#WP_FLAGS  += -wp-prop MultisetTransposition


TESTOBJ += -lmutating

