
include ../../Config/example.mk

WP_TIMEOUT=20
#WP_FLAGS += -wp-prop  remove
#WP_FLAGS += -wp-prop  partition
#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-bhv not_equal
#WP_FLAGS += -wp-prop @assert
#WP_FLAGS += -wp-prop="-@lemma"
#WP_FLAGS += -wp-prop @lemma

