
CMD=\\removecopythree
SEC=sec:removecopy3

include ../../example.mk

#WP_FLAGS += -wp-prop  RemovePartitionUpperBound
#WP_FLAGS += -wp-prop  size
#WP_FLAGS += -wp-prop unchanged
#WP_FLAGS += -wp-bhv not_equal
#WP_FLAGS += -wp-prop @assert
#WP_FLAGS += -wp-prop @lemma
#WP_FLAGS += -wp-prop="-@lemma"

