
# Makefile (directory-local configuration)

TOP_DIR    ?= $(abspath ../..)
CONFIG_DIR := $(TOP_DIR)/Config
ADDITIONAL  = Stack Nonmutating

include $(CONFIG_DIR)/examples.mk

# set special timeout
#stack_empty.wp stack_empty.wplog: WP_TIMEOUT = 4
