(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require bool.Bool.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.
Require real.Real.
Require real.RealInfix.
Require real.FromInt.
Require map.Map.

Parameter eqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom eqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  ((x = y) -> ((eqb x y) = Init.Datatypes.true)) /\
  (~ (x = y) -> ((eqb x y) = Init.Datatypes.false)).

Parameter neqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom neqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  (~ (x = y) -> ((neqb x y) = Init.Datatypes.true)) /\
  ((x = y) -> ((neqb x y) = Init.Datatypes.false)).

Parameter zlt: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zlt'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x < y)%Z -> ((zlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%Z -> ((zlt x y) = Init.Datatypes.false)).

Parameter zleq:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zleq'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x <= y)%Z -> ((zleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%Z -> ((zleq x y) = Init.Datatypes.false)).

Parameter rlt:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rlt'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x < y)%R -> ((rlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%R -> ((rlt x y) = Init.Datatypes.false)).

Parameter rleq:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rleq'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x <= y)%R -> ((rleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%R -> ((rleq x y) = Init.Datatypes.false)).

(* Why3 assumption *)
Definition real_of_int (x:Numbers.BinNums.Z) : Reals.Rdefinitions.R :=
  BuiltIn.IZR x.

Axiom c_euclidian :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z), ~ (d = 0%Z) ->
  (n = (((ZArith.BinInt.Z.quot n d) * d)%Z + (ZArith.BinInt.Z.rem n d))%Z).

Axiom cmod_remainder :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z),
  ((0%Z <= n)%Z -> (0%Z < d)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) < d)%Z) /\
  ((n <= 0%Z)%Z -> (0%Z < d)%Z ->
   ((-d)%Z < (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z) /\
  ((0%Z <= n)%Z -> (d < 0%Z)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) < (-d)%Z)%Z) /\
  ((n <= 0%Z)%Z -> (d < 0%Z)%Z ->
   (d < (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z).

Axiom cdiv_neutral :
  forall (a:Numbers.BinNums.Z), ((ZArith.BinInt.Z.quot a 1%Z) = a).

Axiom cdiv_inv :
  forall (a:Numbers.BinNums.Z), ~ (a = 0%Z) ->
  ((ZArith.BinInt.Z.quot a a) = 1%Z).

Axiom cdiv_closed_remainder :
  forall (a:Numbers.BinNums.Z) (b:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= a)%Z -> (0%Z <= b)%Z ->
  (0%Z <= (b - a)%Z)%Z /\ ((b - a)%Z < n)%Z ->
  ((ZArith.BinInt.Z.rem a n) = (ZArith.BinInt.Z.rem b n)) -> (a = b).

(* Why3 assumption *)
Inductive addr :=
  | addr'mk : Numbers.BinNums.Z -> Numbers.BinNums.Z -> addr.
Axiom addr_WhyType : WhyType addr.
Existing Instance addr_WhyType.

(* Why3 assumption *)
Definition base (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x
  end.

(* Why3 assumption *)
Definition offset (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x1
  end.

(* Why3 assumption *)
Definition malloc := Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition null : addr := addr'mk 0%Z 0%Z.

(* Why3 assumption *)
Definition global (b:Numbers.BinNums.Z) : addr := addr'mk b 0%Z.

Parameter addr_le: addr -> addr -> Prop.

Parameter addr_lt: addr -> addr -> Prop.

Parameter addr_le_bool: addr -> addr -> Init.Datatypes.bool.

Parameter addr_lt_bool: addr -> addr -> Init.Datatypes.bool.

Axiom addr_le_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_le p q <-> ((offset p) <= (offset q))%Z.

Axiom addr_lt_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_lt p q <-> ((offset p) < (offset q))%Z.

Axiom addr_le_bool_def :
  forall (p:addr) (q:addr),
  addr_le p q <-> ((addr_le_bool p q) = Init.Datatypes.true).

Axiom addr_lt_bool_def :
  forall (p:addr) (q:addr),
  addr_lt p q <-> ((addr_lt_bool p q) = Init.Datatypes.true).

(* Why3 assumption *)
Definition shift (p:addr) (k:Numbers.BinNums.Z) : addr :=
  addr'mk (base p) ((offset p) + k)%Z.

(* Why3 assumption *)
Definition valid_rw (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  (0%Z < (base p))%Z /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_rd (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_obj (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr) :
    Prop :=
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\
  ((offset p) <= (m (base p)))%Z /\ (0%Z < (m (base p)))%Z.

(* Why3 assumption *)
Definition invalid (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (n <= 0%Z)%Z \/
  ((base p) = 0%Z) \/
  ((m (base p)) <= (offset p))%Z \/ (((offset p) + n)%Z <= 0%Z)%Z.

Axiom valid_rw_rd :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  forall (n:Numbers.BinNums.Z), valid_rw m p n -> valid_rd m p n.

Axiom valid_string :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  ((base p) < 0%Z)%Z ->
  (0%Z <= (offset p))%Z /\ ((offset p) < (m (base p)))%Z ->
  valid_rd m p 1%Z /\ ~ valid_rw m p 1%Z.

(* Why3 assumption *)
Definition included (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (0%Z < lp)%Z ->
  (0%Z <= lq)%Z /\
  ((base p) = (base q)) /\
  ((offset q) <= (offset p))%Z /\
  (((offset p) + lp)%Z <= ((offset q) + lq)%Z)%Z.

(* Why3 assumption *)
Definition separated (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (lp <= 0%Z)%Z \/
  (lq <= 0%Z)%Z \/
  ~ ((base p) = (base q)) \/
  (((offset q) + lq)%Z <= (offset p))%Z \/
  (((offset p) + lp)%Z <= (offset q))%Z.

Axiom separated_1 :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (i:Numbers.BinNums.Z)
    (j:Numbers.BinNums.Z),
  separated p lp q lq ->
  ((offset p) <= i)%Z /\ (i < ((offset p) + lp)%Z)%Z ->
  ((offset q) <= j)%Z /\ (j < ((offset q) + lq)%Z)%Z ->
  ~ ((addr'mk (base p) i) = (addr'mk (base q) j)).

Axiom separated_included :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z), (0%Z < lp)%Z ->
  (0%Z < lq)%Z -> separated p lp q lq -> ~ included p lp q lq.

Axiom included_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> included q lq r lr -> included p lp r lr.

Axiom separated_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> separated q lq r lr -> separated p lp r lr.

Axiom separated_sym :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z),
  separated p lp q lq <-> separated q lq p lp.

Parameter binit: Numbers.BinNums.Z -> Prop.

Parameter region: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Parameter linked: (Numbers.BinNums.Z -> Numbers.BinNums.Z) -> Prop.

Parameter static_malloc: Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition statically_allocated (base1:Numbers.BinNums.Z) : Prop :=
  (base1 = 0%Z) \/ (0%Z < (static_malloc base1))%Z.

Axiom valid_pointers_are_statically_allocated :
  forall (a:addr) (m:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  (0%Z < n)%Z -> valid_rd m a n -> statically_allocated (base a).

Parameter int_of_addr: addr -> Numbers.BinNums.Z.

Parameter addr_of_int: Numbers.BinNums.Z -> addr.

Axiom addr_of_null : ((int_of_addr null) = 0%Z).

Axiom addr_of_int_bijection :
  forall (p:addr), statically_allocated (base p) ->
  ((addr_of_int (int_of_addr p)) = p).

Axiom table : Type.
Parameter table_WhyType : WhyType table.
Existing Instance table_WhyType.

Parameter table_of_base: Numbers.BinNums.Z -> table.

Parameter table_to_offset: table -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom table_to_offset_zero :
  forall (t:table), ((table_to_offset t 0%Z) = 0%Z).

Axiom table_to_offset_monotonic :
  forall (t:table), forall (o1:Numbers.BinNums.Z) (o2:Numbers.BinNums.Z),
  (o1 <= o2)%Z <-> ((table_to_offset t o1) <= (table_to_offset t o2))%Z.

Parameter L_CountNotEqual_1_:
  (addr -> Numbers.BinNums.Z) -> addr -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom L_CountNotEqual_1__def :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (v:Numbers.BinNums.Z),
  let x := ((-1%Z)%Z + n)%Z in
  ((n <= m)%Z -> ((L_CountNotEqual_1_ Mint a m n v) = 0%Z)) /\
  (~ (n <= m)%Z ->
   (((Mint (shift a x)) = v) ->
    ((L_CountNotEqual_1_ Mint a m n v) =
     ((L_CountNotEqual_1_ Mint a m x v) + 0%Z)%Z)) /\
   (~ ((Mint (shift a x)) = v) ->
    ((L_CountNotEqual_1_ Mint a m n v) =
     ((L_CountNotEqual_1_ Mint a m x v) + 1%Z)%Z))).

(* Why3 assumption *)
Definition is_bool (x:Numbers.BinNums.Z) : Prop := (x = 0%Z) \/ (x = 1%Z).

(* Why3 assumption *)
Definition is_uint8 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 256%Z)%Z.

(* Why3 assumption *)
Definition is_sint8 (x:Numbers.BinNums.Z) : Prop :=
  ((-128%Z)%Z <= x)%Z /\ (x < 128%Z)%Z.

(* Why3 assumption *)
Definition is_uint16 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 65536%Z)%Z.

(* Why3 assumption *)
Definition is_sint16 (x:Numbers.BinNums.Z) : Prop :=
  ((-32768%Z)%Z <= x)%Z /\ (x < 32768%Z)%Z.

(* Why3 assumption *)
Definition is_uint32 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 4294967296%Z)%Z.

(* Why3 assumption *)
Definition is_sint32 (x:Numbers.BinNums.Z) : Prop :=
  ((-2147483648%Z)%Z <= x)%Z /\ (x < 2147483648%Z)%Z.

(* Why3 assumption *)
Definition is_uint64 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 18446744073709551616%Z)%Z.

(* Why3 assumption *)
Definition is_sint64 (x:Numbers.BinNums.Z) : Prop :=
  ((-9223372036854775808%Z)%Z <= x)%Z /\ (x < 9223372036854775808%Z)%Z.

Axiom is_bool0 : is_bool 0%Z.

Axiom is_bool1 : is_bool 1%Z.

Parameter to_bool: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_bool'def :
  forall (x:Numbers.BinNums.Z),
  ((x = 0%Z) -> ((to_bool x) = 0%Z)) /\ (~ (x = 0%Z) -> ((to_bool x) = 1%Z)).

Parameter to_uint8: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint8'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z -> ((to_uint8 x) = (to_uint8 (x + 256%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((256%Z <= x)%Z -> ((to_uint8 x) = (to_uint8 (x - 256%Z)%Z))) /\
   (~ (256%Z <= x)%Z -> ((to_uint8 x) = x))).

Parameter to_sint8: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint8'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-128%Z)%Z)%Z -> ((to_sint8 x) = (to_sint8 (x + 256%Z)%Z))) /\
  (~ (x < (-128%Z)%Z)%Z ->
   ((128%Z <= x)%Z -> ((to_sint8 x) = (to_sint8 (x - 256%Z)%Z))) /\
   (~ (128%Z <= x)%Z -> ((to_sint8 x) = x))).

Parameter to_uint16: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint16'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z -> ((to_uint16 x) = (to_uint16 (x + 65536%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((65536%Z <= x)%Z -> ((to_uint16 x) = (to_uint16 (x - 65536%Z)%Z))) /\
   (~ (65536%Z <= x)%Z -> ((to_uint16 x) = x))).

Parameter to_sint16: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint16'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-32768%Z)%Z)%Z -> ((to_sint16 x) = (to_sint16 (x + 65536%Z)%Z))) /\
  (~ (x < (-32768%Z)%Z)%Z ->
   ((32768%Z <= x)%Z -> ((to_sint16 x) = (to_sint16 (x - 65536%Z)%Z))) /\
   (~ (32768%Z <= x)%Z -> ((to_sint16 x) = x))).

Parameter to_uint32: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint32'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z -> ((to_uint32 x) = (to_uint32 (x + 4294967296%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((4294967296%Z <= x)%Z ->
    ((to_uint32 x) = (to_uint32 (x - 4294967296%Z)%Z))) /\
   (~ (4294967296%Z <= x)%Z -> ((to_uint32 x) = x))).

Parameter to_sint32: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint32'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-2147483648%Z)%Z)%Z ->
   ((to_sint32 x) = (to_sint32 (x + 4294967296%Z)%Z))) /\
  (~ (x < (-2147483648%Z)%Z)%Z ->
   ((2147483648%Z <= x)%Z ->
    ((to_sint32 x) = (to_sint32 (x - 4294967296%Z)%Z))) /\
   (~ (2147483648%Z <= x)%Z -> ((to_sint32 x) = x))).

Parameter to_uint64: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint64'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z ->
   ((to_uint64 x) = (to_uint64 (x + 18446744073709551616%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((18446744073709551616%Z <= x)%Z ->
    ((to_uint64 x) = (to_uint64 (x - 18446744073709551616%Z)%Z))) /\
   (~ (18446744073709551616%Z <= x)%Z -> ((to_uint64 x) = x))).

Parameter to_sint64: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint64'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-9223372036854775808%Z)%Z)%Z ->
   ((to_sint64 x) = (to_sint64 (x + 18446744073709551616%Z)%Z))) /\
  (~ (x < (-9223372036854775808%Z)%Z)%Z ->
   ((9223372036854775808%Z <= x)%Z ->
    ((to_sint64 x) = (to_sint64 (x - 18446744073709551616%Z)%Z))) /\
   (~ (9223372036854775808%Z <= x)%Z -> ((to_sint64 x) = x))).

Parameter two_power_abs: Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition is_uint (n:Numbers.BinNums.Z) (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < (two_power_abs n))%Z.

(* Why3 assumption *)
Definition is_sint (n:Numbers.BinNums.Z) (x:Numbers.BinNums.Z) : Prop :=
  ((-(two_power_abs n))%Z <= x)%Z /\ (x < (two_power_abs n))%Z.

Parameter to_uint:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Parameter to_sint:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom is_to_uint8 : forall (x:Numbers.BinNums.Z), is_uint8 (to_uint8 x).

Axiom is_to_sint8 : forall (x:Numbers.BinNums.Z), is_sint8 (to_sint8 x).

Axiom is_to_uint16 : forall (x:Numbers.BinNums.Z), is_uint16 (to_uint16 x).

Axiom is_to_sint16 : forall (x:Numbers.BinNums.Z), is_sint16 (to_sint16 x).

Axiom is_to_uint32 : forall (x:Numbers.BinNums.Z), is_uint32 (to_uint32 x).

Axiom is_to_sint32 : forall (x:Numbers.BinNums.Z), is_sint32 (to_sint32 x).

Axiom is_to_uint64 : forall (x:Numbers.BinNums.Z), is_uint64 (to_uint64 x).

Axiom is_to_sint64 : forall (x:Numbers.BinNums.Z), is_sint64 (to_sint64 x).

Axiom id_uint8 :
  forall (x:Numbers.BinNums.Z), is_uint8 x -> ((to_uint8 x) = x).

Axiom id_sint8 :
  forall (x:Numbers.BinNums.Z), is_sint8 x -> ((to_sint8 x) = x).

Axiom id_uint16 :
  forall (x:Numbers.BinNums.Z), is_uint16 x -> ((to_uint16 x) = x).

Axiom id_sint16 :
  forall (x:Numbers.BinNums.Z), is_sint16 x -> ((to_sint16 x) = x).

Axiom id_uint32 :
  forall (x:Numbers.BinNums.Z), is_uint32 x -> ((to_uint32 x) = x).

Axiom id_sint32 :
  forall (x:Numbers.BinNums.Z), is_sint32 x -> ((to_sint32 x) = x).

Axiom id_uint64 :
  forall (x:Numbers.BinNums.Z), is_uint64 x -> ((to_uint64 x) = x).

Axiom id_sint64 :
  forall (x:Numbers.BinNums.Z), is_sint64 x -> ((to_sint64 x) = x).

Axiom id_uint8_inl :
  forall (x:Numbers.BinNums.Z), (0%Z <= x)%Z /\ (x < 256%Z)%Z ->
  ((to_uint8 x) = x).

Axiom id_sint8_inl :
  forall (x:Numbers.BinNums.Z), ((-128%Z)%Z <= x)%Z /\ (x < 128%Z)%Z ->
  ((to_sint8 x) = x).

Axiom id_uint16_inl :
  forall (x:Numbers.BinNums.Z), (0%Z <= x)%Z /\ (x < 65536%Z)%Z ->
  ((to_uint16 x) = x).

Axiom id_sint16_inl :
  forall (x:Numbers.BinNums.Z), ((-32768%Z)%Z <= x)%Z /\ (x < 32768%Z)%Z ->
  ((to_sint16 x) = x).

Axiom id_uint32_inl :
  forall (x:Numbers.BinNums.Z), (0%Z <= x)%Z /\ (x < 4294967296%Z)%Z ->
  ((to_uint32 x) = x).

Axiom id_sint32_inl :
  forall (x:Numbers.BinNums.Z),
  ((-2147483648%Z)%Z <= x)%Z /\ (x < 2147483648%Z)%Z -> ((to_sint32 x) = x).

Axiom id_uint64_inl :
  forall (x:Numbers.BinNums.Z),
  (0%Z <= x)%Z /\ (x < 18446744073709551616%Z)%Z -> ((to_uint64 x) = x).

Axiom id_sint64_inl :
  forall (x:Numbers.BinNums.Z),
  ((-9223372036854775808%Z)%Z <= x)%Z /\ (x < 9223372036854775808%Z)%Z ->
  ((to_sint64 x) = x).

Axiom proj_int8 :
  forall (x:Numbers.BinNums.Z), ((to_sint8 (to_uint8 x)) = (to_sint8 x)).

Axiom proj_int16 :
  forall (x:Numbers.BinNums.Z), ((to_sint16 (to_uint16 x)) = (to_sint16 x)).

Axiom proj_int32 :
  forall (x:Numbers.BinNums.Z), ((to_sint32 (to_uint32 x)) = (to_sint32 x)).

Axiom proj_int64 :
  forall (x:Numbers.BinNums.Z), ((to_sint64 (to_uint64 x)) = (to_sint64 x)).

(* Why3 assumption *)
Definition is_sint32_chunk (m:addr -> Numbers.BinNums.Z) : Prop :=
  forall (a:addr), is_sint32 (m a).

Axiom Q_CountNotEqual_Empty :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (n <= m)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_CountNotEqual_1_ Mint a m n v) = 0%Z).

Axiom Q_CountNotEqual_Hit :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := Mint (shift a n) in
  ~ (x = v) -> (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  is_sint32 x ->
  ((1%Z + (L_CountNotEqual_1_ Mint a m n v))%Z =
   (L_CountNotEqual_1_ Mint a m (1%Z + n)%Z v)).

Axiom Q_CountNotEqual_Miss :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := Mint (shift a n) in
  (x = v) -> (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  is_sint32 x ->
  ((L_CountNotEqual_1_ Mint a m (1%Z + n)%Z v) =
   (L_CountNotEqual_1_ Mint a m n v)).

Axiom Q_CountNotEqual_Lower :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  (0%Z <= (L_CountNotEqual_1_ Mint a m n v))%Z.

Axiom Q_CountNotEqual_Upper :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((m + (L_CountNotEqual_1_ Mint a m n v))%Z <= n)%Z.

Axiom Q_CountNotEqual_WeaklyIncreasing :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_CountNotEqual_1_ Mint a m n v) <=
   (L_CountNotEqual_1_ Mint a m (1%Z + n)%Z v))%Z.

Axiom Q_CountNotEqual_Increasing :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (k:Numbers.BinNums.Z) (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (m <= k)%Z -> (k <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_CountNotEqual_1_ Mint a m k v) <= (L_CountNotEqual_1_ Mint a m n v))%Z.

(* Why3 assumption *)
Definition P_Unchanged_1_ (Mint:addr -> Numbers.BinNums.Z)
    (Mint1:addr -> Numbers.BinNums.Z) (a:addr) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) : Prop :=
  forall (i:Numbers.BinNums.Z),
  let a1 := shift a i in (m <= i)%Z -> (i < n)%Z -> ((Mint1 a1) = (Mint a1)).

Axiom Q_CountNotEqual_Unchanged :
  forall (Mint:addr -> Numbers.BinNums.Z) (Mint1:addr -> Numbers.BinNums.Z)
    (a:addr) (v:Numbers.BinNums.Z) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  is_sint32_chunk Mint -> is_sint32_chunk Mint1 -> is_sint32 v ->
  P_Unchanged_1_ Mint Mint1 a m n ->
  ((L_CountNotEqual_1_ Mint1 a m n v) = (L_CountNotEqual_1_ Mint a m n v)).

Parameter L_Count_1_:
  (addr -> Numbers.BinNums.Z) -> addr -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom L_Count_1__def :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (v:Numbers.BinNums.Z),
  let x := ((-1%Z)%Z + n)%Z in
  ((n <= m)%Z -> ((L_Count_1_ Mint a m n v) = 0%Z)) /\
  (~ (n <= m)%Z ->
   (((Mint (shift a x)) = v) ->
    ((L_Count_1_ Mint a m n v) = ((L_Count_1_ Mint a m x v) + 1%Z)%Z)) /\
   (~ ((Mint (shift a x)) = v) ->
    ((L_Count_1_ Mint a m n v) = ((L_Count_1_ Mint a m x v) + 0%Z)%Z))).

Axiom Q_Count_Empty :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (n <= m)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_Count_1_ Mint a m n v) = 0%Z).

Axiom Q_Count_Hit :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (m:Numbers.BinNums.Z),
  let x := ((-1%Z)%Z + n)%Z in
  let x1 := Mint (shift a x) in
  (x1 = v) -> (m < n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  is_sint32 x1 ->
  ((1%Z + (L_Count_1_ Mint a m x v))%Z = (L_Count_1_ Mint a m n v)).

Axiom Q_Count_Miss :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (m:Numbers.BinNums.Z),
  let x := ((-1%Z)%Z + n)%Z in
  let x1 := Mint (shift a x) in
  ~ (x1 = v) -> (m < n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  is_sint32 x1 -> ((L_Count_1_ Mint a m x v) = (L_Count_1_ Mint a m n v)).

Axiom Q_Count_One :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := (1%Z + n)%Z in
  (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  (((L_Count_1_ Mint a m n v) + (L_Count_1_ Mint a n x v))%Z =
   (L_Count_1_ Mint a m x v)).

Axiom Q_Count_Single :
  forall (Mint:addr -> Numbers.BinNums.Z) (Mint1:addr -> Numbers.BinNums.Z)
    (a:addr) (b:addr) (v:Numbers.BinNums.Z) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  let x := Mint1 (shift a m) in
  let x1 := Mint (shift b n) in
  (x = x1) -> is_sint32_chunk Mint -> is_sint32_chunk Mint1 -> is_sint32 v ->
  is_sint32 x1 -> is_sint32 x ->
  ((L_Count_1_ Mint1 a m (1%Z + m)%Z v) =
   (L_Count_1_ Mint b n (1%Z + n)%Z v)).

(* Why3 assumption *)
Definition P_Equal_1_ (Mint:addr -> Numbers.BinNums.Z)
    (Mint1:addr -> Numbers.BinNums.Z) (a:addr) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (b:addr) : Prop :=
  forall (i:Numbers.BinNums.Z), (m <= i)%Z -> (i < n)%Z ->
  ((Mint1 (shift a i)) = (Mint (shift b i))).

(* Why3 assumption *)
Definition P_Equal_3_ (Mint:addr -> Numbers.BinNums.Z)
    (Mint1:addr -> Numbers.BinNums.Z) (a:addr) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (b:addr) (p:Numbers.BinNums.Z) : Prop :=
  P_Equal_1_ Mint Mint1 (shift a m) 0%Z (n + ((-1%Z)%Z * m)%Z)%Z (shift b p).

(* Why3 assumption *)
Definition P_Equal_4_ (Mint:addr -> Numbers.BinNums.Z)
    (Mint1:addr -> Numbers.BinNums.Z) (a:addr) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (p:Numbers.BinNums.Z) : Prop :=
  P_Equal_3_ Mint Mint1 a m n a p.

Axiom Q_Count_Equal :
  forall (Mint:addr -> Numbers.BinNums.Z) (Mint1:addr -> Numbers.BinNums.Z)
    (a:addr) (v:Numbers.BinNums.Z) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (p:Numbers.BinNums.Z),
  (0%Z <= m)%Z -> (m <= n)%Z -> is_sint32_chunk Mint ->
  is_sint32_chunk Mint1 -> is_sint32 v -> P_Equal_4_ Mint Mint1 a m n p ->
  ((L_Count_1_ Mint a p ((n + p)%Z + ((-1%Z)%Z * m)%Z)%Z v) =
   (L_Count_1_ Mint1 a m n v)).

Axiom Q_Count_Unchanged :
  forall (Mint:addr -> Numbers.BinNums.Z) (Mint1:addr -> Numbers.BinNums.Z)
    (a:addr) (v:Numbers.BinNums.Z) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  is_sint32_chunk Mint -> is_sint32_chunk Mint1 -> is_sint32 v ->
  P_Unchanged_1_ Mint Mint1 a m n ->
  ((L_Count_1_ Mint1 a m n v) = (L_Count_1_ Mint a m n v)).

Axiom Q_Count_Union :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (k:Numbers.BinNums.Z) (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= k)%Z -> (k <= m)%Z -> (m <= n)%Z -> is_sint32_chunk Mint ->
  is_sint32 v ->
  (((L_Count_1_ Mint a k m v) + (L_Count_1_ Mint a m n v))%Z =
   (L_Count_1_ Mint a k n v)).

Axiom Q_Count_Cut :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (k:Numbers.BinNums.Z) (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := (1%Z + m)%Z in
  (0%Z <= k)%Z -> (k <= m)%Z -> (m < n)%Z -> is_sint32_chunk Mint ->
  is_sint32 v ->
  ((((L_Count_1_ Mint a k m v) + (L_Count_1_ Mint a m x v))%Z +
    (L_Count_1_ Mint a x n v))%Z
   = (L_Count_1_ Mint a k n v)).

Axiom Q_Count_Single_Bounds :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  let x := L_Count_1_ Mint a n (1%Z + n)%Z v in
  is_sint32_chunk Mint -> is_sint32 v -> (0%Z <= x)%Z /\ (x <= 1%Z)%Z.

Axiom Q_Count_Bounds :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := L_Count_1_ Mint a m n v in
  (0%Z <= m)%Z -> (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  (0%Z <= x)%Z /\ ((m + x)%Z <= n)%Z.

Axiom Q_Count_Increasing :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z) (p:Numbers.BinNums.Z),
  (m <= n)%Z -> (n <= p)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_Count_1_ Mint a m n v) <= (L_Count_1_ Mint a m p v))%Z.

Axiom Q_Count_Single_Shift :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  (0%Z <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_Count_1_ Mint (shift a n) 0%Z 1%Z v) =
   (L_Count_1_ Mint a n (1%Z + n)%Z v)).

Axiom Q_Count_Shift :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= m)%Z -> (0%Z <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_Count_1_ Mint (shift a m) 0%Z n v) = (L_Count_1_ Mint a m (m + n)%Z v)).

Axiom Q_CountNotEqual_Count :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  (((m + (L_Count_1_ Mint a m n v))%Z + (L_CountNotEqual_1_ Mint a m n v))%Z
   = n).

Axiom Q_CountNotEqual_Union :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (k:Numbers.BinNums.Z) (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= k)%Z -> (k <= m)%Z -> (m <= n)%Z -> is_sint32_chunk Mint ->
  is_sint32 v ->
  (((L_CountNotEqual_1_ Mint a k m v) + (L_CountNotEqual_1_ Mint a m n v))%Z
   = (L_CountNotEqual_1_ Mint a k n v)).

Parameter L_FindNotEqual_1_:
  (addr -> Numbers.BinNums.Z) -> addr -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom L_FindNotEqual_1__def :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (v:Numbers.BinNums.Z),
  let x := ((-1%Z)%Z + n)%Z in
  let x1 := L_FindNotEqual_1_ Mint a m x v in
  let x2 := ((-1%Z)%Z * m)%Z in
  ((n <= m)%Z -> ((L_FindNotEqual_1_ Mint a m n v) = 0%Z)) /\
  (~ (n <= m)%Z ->
   ((0%Z <= x1)%Z /\ (((2%Z + m)%Z + x1)%Z <= n)%Z ->
    ((L_FindNotEqual_1_ Mint a m n v) = x1)) /\
   (~ ((0%Z <= x1)%Z /\ (((2%Z + m)%Z + x1)%Z <= n)%Z) ->
    (((Mint (shift a x)) = v) ->
     ((L_FindNotEqual_1_ Mint a m n v) = (n + x2)%Z)) /\
    (~ ((Mint (shift a x)) = v) ->
     ((L_FindNotEqual_1_ Mint a m n v) = (((-1%Z)%Z + n)%Z + x2)%Z)))).

Axiom Q_FindNotEqual_Empty :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (n <= m)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_FindNotEqual_1_ Mint a m n v) = 0%Z).

Axiom Q_FindNotEqual_Hit :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := L_FindNotEqual_1_ Mint a m n v in
  (m <= n)%Z -> ((m + x)%Z < n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_FindNotEqual_1_ Mint a m (1%Z + n)%Z v) = x).

Axiom Q_FindNotEqual_MissHit :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := Mint (shift a n) in
  ~ (x = v) -> ((m + (L_FindNotEqual_1_ Mint a m n v))%Z = n) ->
  (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v -> is_sint32 x ->
  ((m + (L_FindNotEqual_1_ Mint a m (1%Z + n)%Z v))%Z = n).

Axiom Q_FindNotEqual_MissMiss :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := Mint (shift a n) in
  let x1 := (1%Z + n)%Z in
  (x = v) -> ((m + (L_FindNotEqual_1_ Mint a m n v))%Z = n) -> (m <= n)%Z ->
  is_sint32_chunk Mint -> is_sint32 v -> is_sint32 x ->
  ((m + (L_FindNotEqual_1_ Mint a m x1 v))%Z = x1).

Axiom Q_FindNotEqual_Lower :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  is_sint32_chunk Mint -> is_sint32 v ->
  (0%Z <= (L_FindNotEqual_1_ Mint a m n v))%Z.

Axiom Q_FindNotEqual_Upper :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((m + (L_FindNotEqual_1_ Mint a m n v))%Z <= n)%Z.

Axiom Q_FindNotEqual_Unchanged :
  forall (Mint:addr -> Numbers.BinNums.Z) (Mint1:addr -> Numbers.BinNums.Z)
    (a:addr) (v:Numbers.BinNums.Z) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  is_sint32_chunk Mint -> is_sint32_chunk Mint1 -> is_sint32 v ->
  P_Unchanged_1_ Mint Mint1 a m n ->
  ((L_FindNotEqual_1_ Mint1 a m n v) = (L_FindNotEqual_1_ Mint a m n v)).

Axiom Q_FindNotEqual_WeaklyIncreasing :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_FindNotEqual_1_ Mint a m n v) <=
   (L_FindNotEqual_1_ Mint a m (1%Z + n)%Z v))%Z.

Axiom Q_FindNotEqual_Increasing :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (k:Numbers.BinNums.Z) (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (m <= k)%Z -> (k <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_FindNotEqual_1_ Mint a m k v) <= (L_FindNotEqual_1_ Mint a m n v))%Z.

Axiom Q_FindNotEqual_Limit :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (k:Numbers.BinNums.Z) (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := Mint (shift a k) in
  ~ (x = v) -> (m <= k)%Z -> (k < n)%Z -> is_sint32_chunk Mint ->
  is_sint32 v -> is_sint32 x ->
  ((m + (L_FindNotEqual_1_ Mint a m n v))%Z <= k)%Z.

(* Why3 assumption *)
Definition P_AllEqual_1_ (Mint:addr -> Numbers.BinNums.Z) (a:addr)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z) (v:Numbers.BinNums.Z) : Prop :=
  forall (i:Numbers.BinNums.Z), (m <= i)%Z -> (i < n)%Z ->
  ((Mint (shift a i)) = v).

(* Why3 assumption *)
Definition P_AllEqual_2_ (Mint:addr -> Numbers.BinNums.Z) (a:addr)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z) : Prop :=
  P_AllEqual_1_ Mint a m n (Mint (shift a m)).

(* Why3 assumption *)
Definition P_SomeNotEqual_1_ (Mint:addr -> Numbers.BinNums.Z) (a:addr)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z) (v:Numbers.BinNums.Z) : Prop :=
  exists i:Numbers.BinNums.Z,
  (~ ((Mint (shift a i)) = v) /\ (m <= i)%Z) /\ (i < n)%Z.

Axiom Q_NotAllEqual_SomeNotEqual :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  is_sint32_chunk Mint -> is_sint32 v -> ~ P_AllEqual_1_ Mint a m n v ->
  P_SomeNotEqual_1_ Mint a m n v.

Axiom Q_SomeNotEqual_NotAllEqual :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  is_sint32_chunk Mint -> is_sint32 v -> P_SomeNotEqual_1_ Mint a m n v ->
  ~ P_AllEqual_1_ Mint a m n v.

Axiom Q_FindNotEqual_AllEqual :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  P_AllEqual_1_ Mint a m n v ->
  ((m + (L_FindNotEqual_1_ Mint a m n v))%Z = n).

Axiom Q_FindNotEqual_SomeNotEqual :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (k:Numbers.BinNums.Z) (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := Mint (shift a k) in
  ~ (x = v) -> (m <= k)%Z -> (k < n)%Z -> is_sint32_chunk Mint ->
  is_sint32 v -> is_sint32 x -> P_AllEqual_1_ Mint a m k v ->
  ((m + (L_FindNotEqual_1_ Mint a m n v))%Z = k).

Axiom Q_FindNotEqual_ResultAllEqual :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  P_AllEqual_1_ Mint a m (m + (L_FindNotEqual_1_ Mint a m n v))%Z v.

Axiom Q_FindNotEqual_ResultNotEqual :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := L_FindNotEqual_1_ Mint a m n v in
  let x1 := (m + x)%Z in
  let x2 := Mint (shift a x1) in
  (0%Z <= x)%Z -> (x1 < n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  is_sint32 x2 -> ~ (x2 = v).

Parameter L_IndexOfNotEqual:
  (addr -> Numbers.BinNums.Z) -> addr -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom L_IndexOfNotEqual_def :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (n:Numbers.BinNums.Z)
    (v:Numbers.BinNums.Z) (k:Numbers.BinNums.Z),
  let x := L_IndexOfNotEqual Mint a n v ((-1%Z)%Z + k)%Z in
  ((k < 0%Z)%Z -> ((L_IndexOfNotEqual Mint a n v k) = (-1%Z)%Z)) /\
  (~ (k < 0%Z)%Z ->
   ((n <= 0%Z)%Z -> ((L_IndexOfNotEqual Mint a n v k) = 0%Z)) /\
   (~ (n <= 0%Z)%Z ->
    ((k < (L_CountNotEqual_1_ Mint a 0%Z n v))%Z ->
     ((L_IndexOfNotEqual Mint a n v k) =
      ((1%Z + x)%Z + (L_FindNotEqual_1_ Mint a (1%Z + x)%Z n v))%Z)) /\
    (~ (k < (L_CountNotEqual_1_ Mint a 0%Z n v))%Z ->
     ((L_IndexOfNotEqual Mint a n v k) = n)))).

Axiom Q_IndexOfNotEqual_Lower :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (k:Numbers.BinNums.Z),
  (0%Z < n)%Z -> (0%Z <= k)%Z ->
  (k < (L_CountNotEqual_1_ Mint a 0%Z n v))%Z -> is_sint32_chunk Mint ->
  is_sint32 v -> (0%Z <= (L_IndexOfNotEqual Mint a n v k))%Z.

Axiom Q_IndexOfNotEqual_Next :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (k:Numbers.BinNums.Z),
  let x := L_IndexOfNotEqual Mint a n v ((-1%Z)%Z + k)%Z in
  (0%Z <= k)%Z -> (0%Z <= n)%Z ->
  (k < (L_CountNotEqual_1_ Mint a 0%Z n v))%Z -> is_sint32_chunk Mint ->
  is_sint32 v ->
  (((1%Z + x)%Z + (L_FindNotEqual_1_ Mint a (1%Z + x)%Z n v))%Z =
   (L_IndexOfNotEqual Mint a n v k)).

Axiom Q_IndexOfNotEqual_Right :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (k:Numbers.BinNums.Z),
  (0%Z <= n)%Z -> ((L_CountNotEqual_1_ Mint a 0%Z n v) <= k)%Z ->
  is_sint32_chunk Mint -> is_sint32 v ->
  ((L_IndexOfNotEqual Mint a n v k) = n).

Axiom Q_IndexOfNotEqual_Empty :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (k:Numbers.BinNums.Z),
  (n <= 0%Z)%Z -> (0%Z <= k)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_IndexOfNotEqual Mint a n v k) = 0%Z).

Axiom Q_IndexOfNotEqual_Left :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z) (k:Numbers.BinNums.Z),
  (k < 0%Z)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_IndexOfNotEqual Mint a n v k) = (-1%Z)%Z).

Axiom Q_CountNotEqual_AllEqual :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= m)%Z -> (m <= n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  P_AllEqual_1_ Mint a m n v -> ((L_CountNotEqual_1_ Mint a m n v) = 0%Z).

Axiom Q_CountNotEqual_SomeNotEqual :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= m)%Z -> (m < n)%Z -> (0%Z < (L_CountNotEqual_1_ Mint a m n v))%Z ->
  is_sint32_chunk Mint -> is_sint32 v -> P_SomeNotEqual_1_ Mint a m n v.

Axiom Q_CountNotEqual_FindNotEqual :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= m)%Z -> (m < n)%Z -> (0%Z < (L_CountNotEqual_1_ Mint a m n v))%Z ->
  is_sint32_chunk Mint -> is_sint32 v ->
  ((m + (L_FindNotEqual_1_ Mint a m n v))%Z < n)%Z.

Axiom Q_CountNotEqual_Zero :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= m)%Z -> (m < n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  ((L_CountNotEqual_1_ Mint a m (m + (L_FindNotEqual_1_ Mint a m n v))%Z v) =
   0%Z).

Axiom Q_CountNotEqual_Decrement :
  forall (Mint:addr -> Numbers.BinNums.Z) (a:addr) (v:Numbers.BinNums.Z)
    (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= m)%Z -> (m < n)%Z -> is_sint32_chunk Mint -> is_sint32 v ->
  (((L_CountNotEqual_1_ Mint a 0%Z m v) +
    (L_CountNotEqual_1_ Mint a (m + (L_FindNotEqual_1_ Mint a m n v))%Z n v))%Z
   = (L_CountNotEqual_1_ Mint a 0%Z n v)).

Axiom Q_Unchanged_Shrink :
  forall (Mint:addr -> Numbers.BinNums.Z) (Mint1:addr -> Numbers.BinNums.Z)
    (a:addr) (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z)
    (p:Numbers.BinNums.Z) (q:Numbers.BinNums.Z),
  (q <= n)%Z -> (m <= p)%Z -> (p <= q)%Z -> is_sint32_chunk Mint ->
  is_sint32_chunk Mint1 -> P_Unchanged_1_ Mint Mint1 a m n ->
  P_Unchanged_1_ Mint Mint1 a p q.

Axiom Q_Unchanged_Extend :
  forall (Mint:addr -> Numbers.BinNums.Z) (Mint1:addr -> Numbers.BinNums.Z)
    (a:addr) (n:Numbers.BinNums.Z),
  let a1 := shift a n in
  let x := Mint1 a1 in
  let x1 := Mint a1 in
  (x = x1) -> is_sint32_chunk Mint -> is_sint32_chunk Mint1 ->
  P_Unchanged_1_ Mint Mint1 a 0%Z n -> is_sint32 x1 -> is_sint32 x ->
  P_Unchanged_1_ Mint Mint1 a 0%Z (1%Z + n)%Z.

Axiom Q_Unchanged_Shift :
  forall (Mint:addr -> Numbers.BinNums.Z) (Mint1:addr -> Numbers.BinNums.Z)
    (a:addr) (p:Numbers.BinNums.Z) (q:Numbers.BinNums.Z)
    (r:Numbers.BinNums.Z),
  is_sint32_chunk Mint -> is_sint32_chunk Mint1 ->
  P_Unchanged_1_ Mint Mint1 (shift a p) q r ->
  P_Unchanged_1_ Mint Mint1 a (p + q)%Z (p + r)%Z.

Axiom Q_Unchanged_Symmetric :
  forall (Mint:addr -> Numbers.BinNums.Z) (Mint1:addr -> Numbers.BinNums.Z)
    (a:addr) (m:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  is_sint32_chunk Mint1 -> is_sint32_chunk Mint ->
  P_Unchanged_1_ Mint Mint1 a m n -> P_Unchanged_1_ Mint1 Mint a m n.

Axiom Q_Unchanged_Transitive :
  forall (Mint:addr -> Numbers.BinNums.Z) (Mint1:addr -> Numbers.BinNums.Z)
    (Mint2:addr -> Numbers.BinNums.Z) (a:addr) (m:Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  is_sint32_chunk Mint -> is_sint32_chunk Mint2 -> is_sint32_chunk Mint1 ->
  P_Unchanged_1_ Mint Mint1 a m n -> P_Unchanged_1_ Mint1 Mint2 a m n ->
  P_Unchanged_1_ Mint Mint2 a m n.

(* Why3 goal *)
Theorem wp_goal :
  forall (t:addr -> Numbers.BinNums.Z) (a:addr) (i:Numbers.BinNums.Z)
    (i1:Numbers.BinNums.Z) (i2:Numbers.BinNums.Z),
  let x := L_IndexOfNotEqual t a i1 i2 i in
  let x1 := t (shift a x) in
  (0%Z < i1)%Z -> (0%Z <= i)%Z ->
  (i < (L_CountNotEqual_1_ t a 0%Z i1 i2))%Z -> is_sint32_chunk t ->
  is_sint32 i2 -> is_sint32 x1 ->
  (~ (x1 = i2) /\
   ((i + (L_CountNotEqual_1_ t a x i1 i2))%Z =
    (L_CountNotEqual_1_ t a 0%Z i1 i2))) /\
  (x < i1)%Z.
(* Why3 intros t a i i1 i2 x x1 h1 h2 h3 h4 h5 h6. *)
Proof.
  (*
    The goal comes from the ACSL lemma IndexOfNotEqual_Core.  Why3 binds two
    abbreviations ahead of the hypotheses, so introduce and substitute them
    away first, then rename what is left to the vocabulary of the lemma:

      L   : memory (addr -> Z)
      a   : base address
      k   : rank among the elements of a[0..n) that differ from v
      n   : upper bound of the range
      v   : value to compare against

      nPos    : 0 < n
      kLower  : 0 <= k
      kUpper  : k < CountNotEqual(a, n, v)
      L32     : the memory holds sint32 values
      V32     : v is an sint32
      W32     : a[IndexOfNotEqual(a, n, v, k)] is an sint32

    Throughout, p_j abbreviates IndexOfNotEqual(a, n, v, j).
  *)
  Require Import Psatz.
  intros L a k n v.
  intros i a_i.
  subst i a_i.
  intros nPos kLower kUpper L32 V32 W32.

  (*
    The three conjuncts -- a[p_k] <> v, the counting identity, and p_k < n --
    are proved together, by induction on the rank k.  The joint statement is
    what carries the induction: the step case consumes all three at rank z,
    each at a different place, so an induction that carried only one of them
    would have too weak a hypothesis.  The uses are named where they occur.

    kUpper and W32 mention k, so they have to travel with the goal.
    natlike_rec2 supplies the induction 0 -> z -> z + 1 over Z; the sibling
    scripts lemma_IndexOfNotEqual_Lower.v and lemma_IndexOfNotEqual_Unchanged.v
    use natlike_rec3 instead.
  *)
  revert kUpper W32.

  apply natlike_rec2 with (z:=k); auto with zarith.

  (* ------------------------------------------------------------------ *)
  (* Base case: k = 0                                                   *)
  (* ------------------------------------------------------------------ *)
  {
    intros kUpper W32.

    (*
      Unfold p_0.  IndexOfNotEqual is defined from its predecessor, and
      p_(-1) = -1, so p_0 is the first index at or after 0 whose value
      differs from v.
    *)
    rewrite <- Q_IndexOfNotEqual_Next; auto with zarith.
    replace (- (1) + 0)%Z with (-1)%Z by lia.
    rewrite Q_IndexOfNotEqual_Left; auto with zarith.
    replace (1 + - (1))%Z with (0)%Z by lia.

    split.
    {
      split.
      {
        (* a[p_0] <> v: FindNotEqual stops on an element different from v. *)
        apply Q_FindNotEqual_ResultNotEqual; auto with zarith.
        { now apply Q_FindNotEqual_Lower. }
        { apply Q_CountNotEqual_FindNotEqual; auto with zarith. }
      }

      (*
        The counting identity at rank 0.  Every element before p_0 equals v,
        so that prefix contributes nothing and counting from p_0 is the same
        as counting from 0.
      *)
      assert(NoneBeforeFirst:
               (0 + L_CountNotEqual_1_ L a 0 (0 + L_FindNotEqual_1_ L a 0 n v) v = 0)%Z).
      {
        rewrite Q_CountNotEqual_Zero; auto with zarith.
      }
      symmetry.
      rewrite <- Q_CountNotEqual_Union
            with (m:=(0 + L_FindNotEqual_1_ L a 0 n v)%Z); auto with zarith.
      { apply Q_FindNotEqual_Lower; auto with zarith. }
      { apply Q_FindNotEqual_Upper; auto with zarith. }
    }

    (* p_0 < n, because a[0..n) holds at least one element different from v. *)
    apply Q_CountNotEqual_FindNotEqual; auto with zarith.
  }

  (* ------------------------------------------------------------------ *)
  (* Step case: from rank z to rank z + 1                               *)
  (* ------------------------------------------------------------------ *)
  {
    intros z zNN IHz.
    intros kUpper W32.
    replace (Z.succ z) with (1+z)%Z in * by lia.

    (*
      Rank z is in range as well, so the induction hypothesis applies.  Its
      three conjuncts are used below as follows:

        IH_NotEqual  a[p_z] <> v   side condition of Q_CountNotEqual_Hit,
                                   where the counting identity is carried
                                   from rank z to rank z + 1
        IH_Count     the identity  with kUpper it yields MoreAfterIdx, hence
                                   that a next element exists at all
        IH_Upper     p_z < n       side condition of Q_CountNotEqual_Union
                                   inside SplitAfterIdx
    *)
    assert(zInRange: (z < L_CountNotEqual_1_ L a 0 n v)%Z) by lia.
    apply IHz in zInRange; auto with zarith.
    destruct zInRange as [[IH_NotEqual IH_Count] IH_Upper].

    assert(IdxLower: (0 <= L_IndexOfNotEqual L a n v z)%Z).
    {
      apply Q_IndexOfNotEqual_Lower; auto with zarith.
    }

    (*
      Strictly after p_z there is still an element different from v, which is
      what lets p_(z+1) be formed at all.  Split the count at p_z + 1: the
      single cell p_z contributes at most one, while IH_Count and kUpper make
      the whole tail from p_z contribute more than one.
    *)
    assert(MoreAfterIdx:
             (0 < L_CountNotEqual_1_ L a (1 + L_IndexOfNotEqual L a n v z) n v)%Z).
    {
      assert(SplitAfterIdx:
               (L_CountNotEqual_1_ L a (L_IndexOfNotEqual L a n v z) n v =
                 L_CountNotEqual_1_ L a (L_IndexOfNotEqual L a n v z) (1+ L_IndexOfNotEqual L a n v z) v +
                 L_CountNotEqual_1_ L a (1+ L_IndexOfNotEqual L a n v z) n v)%Z).
      {
        rewrite <- Q_CountNotEqual_Union with
          (m := (1+ L_IndexOfNotEqual L a n v z)%Z); auto with zarith.
      }
      enough(0 <= L_CountNotEqual_1_ L a (L_IndexOfNotEqual L a n v z) (1 + L_IndexOfNotEqual L a n v z) v <= 1)%Z by lia.
      split.
      { apply Q_CountNotEqual_Lower; auto with zarith. }
      {
        enough (L_IndexOfNotEqual L a n v z +
                L_CountNotEqual_1_ L a (L_IndexOfNotEqual L a n v z) (1 + L_IndexOfNotEqual L a n v z) v <=
                1 + L_IndexOfNotEqual L a n v z)%Z by lia.
        apply Q_CountNotEqual_Upper; auto with zarith.
      }
    }

    split.
    {
      split.
      {
        (* a[p_(z+1)] <> v, again because FindNotEqual stops on such an element. *)
        rewrite <- Q_IndexOfNotEqual_Next; auto with zarith.
        replace (- (1) + (1 + z))%Z with z by lia.
        apply Q_FindNotEqual_ResultNotEqual; auto with zarith.
        { now apply Q_FindNotEqual_Lower. }
        {
          apply Q_CountNotEqual_FindNotEqual; auto with zarith.
          assert(IdxCountFits:
                   (L_IndexOfNotEqual L a n v z +
                    L_CountNotEqual_1_ L a (L_IndexOfNotEqual L a n v z) n v <= n)%Z).
          { apply Q_CountNotEqual_Upper; auto with zarith. }
          lia.
        }
      }

      (*
        The counting identity at rank z + 1.  Write p for p_z and f for the
        offset that FindNotEqual adds to p + 1, so that p_(z+1) = p + 1 + f.
      *)
      remember (L_IndexOfNotEqual L a n v z) as p.
      symmetry.
      rewrite <- Q_IndexOfNotEqual_Next; auto with zarith.
      replace (- (1) + (1 + z))%Z with z by lia.
      rewrite <- Heqp.
      symmetry in IH_Count.

      remember (L_FindNotEqual_1_ L a (1 + p) n v) as f.

      (* Everything below p + 1, plus everything from p_(z+1) on, is the whole. *)
      assert(SplitAtNext:
               (L_CountNotEqual_1_ L a 0 n v =
                 L_CountNotEqual_1_ L a 0 (1+p) v +
                 L_CountNotEqual_1_ L a (1 + p + L_FindNotEqual_1_ L a (1 + p) n v) n v)%Z).
      {
        rewrite <- Q_CountNotEqual_Decrement with (m := (1+p)%Z); auto with zarith.
        rewrite Heqp.
        assert(IdxCountFits:
                 (L_IndexOfNotEqual L a n v z +
                  L_CountNotEqual_1_ L a (L_IndexOfNotEqual L a n v z) n v <= n)%Z).
        { apply Q_CountNotEqual_Upper; auto with zarith. }
        subst p; lia.
      }

      rewrite <- Heqf in SplitAtNext.
      enough(L_CountNotEqual_1_ L a 0 (1 + p) v = 1 + z)%Z by lia.
      assert(SplitAtIdx:
               (L_CountNotEqual_1_ L a 0 n v =
                 L_CountNotEqual_1_ L a 0 p v + L_CountNotEqual_1_ L a p n v)%Z) by
      (rewrite <- Q_CountNotEqual_Union with (m:=p); auto with zarith).

      (* By IH_Count, exactly z elements different from v lie below p. *)
      assert(CountBeforeIdx: (L_CountNotEqual_1_ L a 0 p v = z)%Z) by lia.
      rewrite <- CountBeforeIdx.
      symmetry.
      assert(SplitAtIdxCell:
               (L_CountNotEqual_1_ L a 0 (1 + p) v =
                 L_CountNotEqual_1_ L a 0 p v + L_CountNotEqual_1_ L a p (1+p) v)%Z) by
         (rewrite <- Q_CountNotEqual_Union with (m:=p); auto with zarith).

      (* The single cell p contributes exactly one, since a[p] <> v by IH_NotEqual. *)
      enough (L_CountNotEqual_1_ L a p (1+p) v = 1)%Z by lia.
      rewrite <- Q_CountNotEqual_Hit; auto with zarith.
      rewrite Q_CountNotEqual_Empty; auto with zarith.
    }

    (* p_(z+1) < n *)
    rewrite <- Q_IndexOfNotEqual_Next; auto with zarith.
    replace (- (1) + (1 + z))%Z with z by lia.
    apply Q_CountNotEqual_FindNotEqual; auto with zarith.
    assert(IdxCountFits:
             (L_IndexOfNotEqual L a n v z +
              L_CountNotEqual_1_ L a (L_IndexOfNotEqual L a n v z) n v <= n)%Z).
    { apply Q_CountNotEqual_Upper; auto with zarith. }
    lia.
  }
Qed.
