(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require bool.Bool.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.
Require real.Real.
Require real.RealInfix.
Require real.FromInt.
Require map.Map.

Parameter eqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom eqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  ((x = y) -> ((eqb x y) = Init.Datatypes.true)) /\
  (~ (x = y) -> ((eqb x y) = Init.Datatypes.false)).

Parameter neqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom neqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  (~ (x = y) -> ((neqb x y) = Init.Datatypes.true)) /\
  ((x = y) -> ((neqb x y) = Init.Datatypes.false)).

Parameter zlt: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zlt'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x < y)%Z -> ((zlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%Z -> ((zlt x y) = Init.Datatypes.false)).

Parameter zleq:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zleq'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x <= y)%Z -> ((zleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%Z -> ((zleq x y) = Init.Datatypes.false)).

Parameter rlt:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rlt'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x < y)%R -> ((rlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%R -> ((rlt x y) = Init.Datatypes.false)).

Parameter rleq:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rleq'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x <= y)%R -> ((rleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%R -> ((rleq x y) = Init.Datatypes.false)).

(* Why3 assumption *)
Definition real_of_int (x:Numbers.BinNums.Z) : Reals.Rdefinitions.R :=
  BuiltIn.IZR x.

Axiom c_euclidian :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z), ~ (d = 0%Z) ->
  (n = (((ZArith.BinInt.Z.quot n d) * d)%Z + (ZArith.BinInt.Z.rem n d))%Z).

Axiom cmod_remainder :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z),
  ((0%Z <= n)%Z -> (0%Z < d)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) < d)%Z) /\
  ((n <= 0%Z)%Z -> (0%Z < d)%Z ->
   ((-d)%Z < (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z) /\
  ((0%Z <= n)%Z -> (d < 0%Z)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) < (-d)%Z)%Z) /\
  ((n <= 0%Z)%Z -> (d < 0%Z)%Z ->
   (d < (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z).

Axiom cdiv_neutral :
  forall (a:Numbers.BinNums.Z), ((ZArith.BinInt.Z.quot a 1%Z) = a).

Axiom cdiv_inv :
  forall (a:Numbers.BinNums.Z), ~ (a = 0%Z) ->
  ((ZArith.BinInt.Z.quot a a) = 1%Z).

Axiom cdiv_closed_remainder :
  forall (a:Numbers.BinNums.Z) (b:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= a)%Z -> (0%Z <= b)%Z ->
  (0%Z <= (b - a)%Z)%Z /\ ((b - a)%Z < n)%Z ->
  ((ZArith.BinInt.Z.rem a n) = (ZArith.BinInt.Z.rem b n)) -> (a = b).

(* Why3 assumption *)
Definition L_HeapLeft (i:Numbers.BinNums.Z) : Numbers.BinNums.Z :=
  (1%Z + (2%Z * i)%Z)%Z.

(* Why3 assumption *)
Definition L_HeapRight (i:Numbers.BinNums.Z) : Numbers.BinNums.Z :=
  (2%Z + (2%Z * i)%Z)%Z.

Axiom Q_Heap_ChildBounds :
  forall (p:Numbers.BinNums.Z),
  let x := L_HeapLeft p in
  (0%Z <= p)%Z -> (p < x)%Z /\ (x < (L_HeapRight p))%Z.

(* Why3 assumption *)
Definition L_HeapParent (i:Numbers.BinNums.Z) : Numbers.BinNums.Z :=
  ZArith.BinInt.Z.quot ((-1%Z)%Z + i)%Z 2%Z.

Axiom Q_Heap_ParentBounds :
  forall (c:Numbers.BinNums.Z),
  let x := L_HeapParent c in (0%Z < c)%Z -> (0%Z <= x)%Z /\ (x < c)%Z.

Axiom Q_Heap_Childs :
  forall (a:Numbers.BinNums.Z) (b:Numbers.BinNums.Z),
  ((L_HeapParent b) = (L_HeapParent a)) -> (0%Z < a)%Z -> (0%Z < b)%Z ->
  ((b = a) \/ ((1%Z + a)%Z = b)) \/ ((1%Z + b)%Z = a).

Axiom Q_Heap_ParentChild :
  forall (c:Numbers.BinNums.Z) (p:Numbers.BinNums.Z),
  ((L_HeapParent c) = p) -> (0%Z < c)%Z ->
  ((L_HeapLeft p) = c) \/ ((L_HeapRight p) = c).

Axiom Q_Heap_ParentRight :
  forall (p:Numbers.BinNums.Z), (0%Z <= p)%Z ->
  ((L_HeapParent (L_HeapRight p)) = p).

Axiom Q_Heap_ParentLeft :
  forall (p:Numbers.BinNums.Z), (0%Z <= p)%Z ->
  ((L_HeapParent (L_HeapLeft p)) = p).

Axiom Q_HeapParent_Zero : ((L_HeapParent 0%Z) = 0%Z).

(* Why3 assumption *)
Inductive P_HeapAncestor: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Prop :=
  | Q_P_HeapAncestor_HeapAncestor_Refl :
      forall (m:Numbers.BinNums.Z), (0%Z <= m)%Z -> P_HeapAncestor m m
  | Q_P_HeapAncestor_HeapAncestor_Step :
      forall (m:Numbers.BinNums.Z) (c:Numbers.BinNums.Z), (0%Z < c)%Z ->
      P_HeapAncestor m (L_HeapParent c) -> P_HeapAncestor m c.

(* Why3 goal *)
Theorem wp_goal :
  forall (i:Numbers.BinNums.Z) (i1:Numbers.BinNums.Z), P_HeapAncestor i1 i ->
  (0%Z <= i1)%Z /\ (i1 <= i)%Z.
Proof.
  Require Import Psatz.

  intros c m H.
  induction H; auto with zarith.
  pose proof (Q_Heap_ParentBounds c H) as Hparent_bounds.
  lia.
Qed.

