
FILE=find_end
CMD=\\findend
SEC=sec:find_end

include ../../Makefile.template

WP_TIMEOUT=100

# verify "first"
#WP_FLAGS += -wp-prop first
#WP_FLAGS += -wp-prop lucy

# verify all but "first"
# WP_FLAGS += -wp-prop="-first"

# verify only lemmas
#WP_FLAGS += -wp-prop @lemma

# verify everything but lemmas
#WP_FLAGS += -wp-prop="-@lemma"


TESTOBJ += ../libnonmutating.a

